language: go

go:
  - 1.7.x
  - 1.8.x
  - 1.9.x
  - 1.10.x
  - tip

before_install:
  - go get -t -v ./...

script:
  - ./go.test.sh
  - go build -o calends.so -buildmode=c-shared ./external

after_success:
  - bash <(curl -s https://codecov.io/bash)
