language: go

sudo: true

go:
  - 1.10.x
  - 1.9.x
  - tip

addons:
  apt:
    packages:
      - valgrind
      - gdb
      - libpcre3-dev

matrix:
  allow_failures:
    - language: php
      php: '7.0'
    - language: php
      php: 'nightly'
  include:
    - &phpDefaults
      language: php
      php: '7.2'
      before_install:
        - export ZEPHIR_VERSION="development"
        - export ZEPHIR_PARSER_VERSION="v1.1.2"
        - export RE2C_VERSION=1.0.3
        - export PHP_MAJOR="$(`phpenv which php` -r 'echo phpversion();' | cut -d '.' -f 1)"
        - export PHP_MINOR="$(`phpenv which php` -r 'echo phpversion();' | cut -d '.' -f 2)"
      install:
        - git clone --depth=1 -v https://github.com/phalcon/zephir -b ${ZEPHIR_VERSION}
        - cd zephir
        - bash ./unit-tests/ci/install-re2c $RE2C_VERSION
        - bash ./unit-tests/ci/install_zephir_parser.sh
        - ./install -c
        - cd ..
      before_script:
        - |
          GIMME_OUTPUT="$(gimme 1.10 | tee -a ${HOME}/.bashrc)" && eval "$GIMME_OUTPUT"
          export GOPATH=${HOME}/gopath
          export PATH=${GOPATH}/bin:$PATH
          mkdir -p ${GOPATH}/src/github.com/danhunsaker/calends
          rsync -az ${TRAVIS_BUILD_DIR}/ ${GOPATH}/src/github.com/danhunsaker/calends/
          export TRAVIS_BUILD_DIR=${GOPATH}/src/github.com/danhunsaker/calends
        - |
          cd ${TRAVIS_BUILD_DIR}
          go get -t -v ./...
        - |
          cd ${TRAVIS_BUILD_DIR}/libcalends
          go build -o libcalends.so -buildmode=c-shared .
        - |
          cd ${TRAVIS_BUILD_DIR}/libcalends/php
          zephir builddev -v
        - echo "set auto-load safe-path /" > ~/.gdbinit
        - ulimit -c unlimited || true
        - echo '/tmp/core_%e.%p' | sudo tee /proc/sys/kernel/core_pattern &> /dev/null
        - sudo chmod +s $(which gdb)
      script:
        - |
          cd ${TRAVIS_BUILD_DIR}/libcalends/php/ext
          TRAVIS='' NO_INTERACTION=true php run-tests.php -P -d "extension=calends.so"
        - ${TRAVIS_BUILD_DIR}/tests/failed_test_info.sh

    - << : *phpDefaults
      php: '7.1'

    - << : *phpDefaults
      php: '7.0'

    - << : *phpDefaults
      php: 'nightly'

before_script:
  - echo "set auto-load safe-path /" > ~/.gdbinit
  - ulimit -c unlimited || true
  - echo '/tmp/core_%e.%p' | sudo tee /proc/sys/kernel/core_pattern &> /dev/null
  - sudo chmod +s $(which gdb)

script:
  - ${TRAVIS_BUILD_DIR}/tests/go.sh
  - |
    cd ${TRAVIS_BUILD_DIR}/libcalends
    go build -o libcalends.so -buildmode=c-shared .

after_failure:
  - ${TRAVIS_BUILD_DIR}/tests/core_dump_info.sh /tmp/

after_success:
  - bash <(curl -s https://codecov.io/bash)
