#!/usr/bin/env bash

set -e

GOPATH=$(go env GOPATH)
TARGETS=${TARGETS:-linux/386,linux/amd64,linux/arm-5,linux/arm-6,linux/arm-7,linux/arm64,darwin/*,windows-4.0/*,windows-6.0/*,windows-6.1/*,windows-6.3/*,windows-10.0/*,windows-11.0/*}

v=$(grep 'Version =' calends.go | awk '{ print $4 }')
VERSION=$(echo v${v//\"/})
unset v

go get github.com/crazy-max/xgo
go install github.com/crazy-max/xgo
${GOPATH}/bin/xgo -buildmode=c-shared -dest=$(pwd)/dist/ -out=libcalends-${VERSION} -targets=${TARGETS} github.com/danhunsaker/calends/libcalends
${GOPATH}/bin/xgo -dest=$(pwd)/dist/bin/ -out=calends-${VERSION} -targets="*/*,${TARGETS}" github.com/danhunsaker/calends/cli
GOOS=js GOARCH=wasm go build -o=$(pwd)/dist/calends-${VERSION}.wasm github.com/danhunsaker/calends

for h in $(find dist/ -name '*.h')
do
  dir=${h/.h/}
  mkdir -p ${dir}
  mv ${dir}.h ${dir}/libcalends.h
  # Linux
  [ -e ${dir}.so ] && mv ${dir}.so ${dir}/libcalends.so
  # Darwin
  [ -e ${dir}.dylib ] && mv ${dir}.dylib ${dir}/libcalends.dylib
  # Windows
  [ -e ${dir}.dll ] && mv ${dir}.dll ${dir}/libcalends.dll

  if [ -e ${dir}/libcalends.dll ]
  then
    zip ${dir}.zip ${dir}/*
  else
    tar czvf ${dir}.tgz -C ${dir} .
  fi

  rm -rf ${dir}
done
