project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
preserve_hierarchy: true

files:
  - source: /docs/.build/gettext/**/*.pot
    translation: /docs/locales/%locale_with_underscore%/LC_MESSAGES/**/%file_name%.po
