name: CI (Test/Build/Release)

on:
  - push
  - pull_request

jobs:
  test:
    name: Test Go ${{ matrix.go }} on ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        go:
          - ~1.19.0
          - ~1.18.0
        include:
          - os: ubuntu-latest
            ext: so
          - os: windows-latest
            ext: dll
          - os: macos-latest
            ext: dylib
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}

      - name: Run Go tests
        run: ./tests/go.sh

      - name: Test building libcalends
        run: go build -v -o libcalends.out -buildmode=c-shared ./libcalends

      - name: Test building cli
        run: go build -v -o calends.out ./cli

  build:
    name: Build Binaries
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}

      - name: Build binaries
        run: ./build-all

      - name: Release binaries
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*
            dist/bin/*
